In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
l=range(100)
%timeit [i**2 for i in l]

17.5 µs ± 2.89 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Creating Array

In [7]:
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [8]:
b=np.array([[1,2],[3,4]])
print(b.ndim)


2


In [9]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 2)
(2, 2, 2)


# functions for creating array

In [11]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [12]:
a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [20]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [21]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
print(np.diag(a))

[1 2 3 4]


# Basic Datatypes

In [25]:
a=np.arange(10)
print(a.dtype)

int32


In [27]:
a=np.arange(10,dtype="float64")
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [29]:
a=np.ones((3,3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


# other datatypes

In [30]:
a=np.array([1+2j,2+3j])
print(a.dtype)

complex128


In [32]:
a=np.array([True,False])
print(a.dtype)

bool


In [33]:
a=np.array(["kav","durga"])
print(a.dtype)

<U5


# indexing and slicing

In [36]:
a=np.arange(10)
print(a[3])

3


In [37]:
a=np.diag([1,2,3])
print(a[2,2])


3


In [41]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [42]:
a=np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [43]:
a=np.arange(10)
a[5:]=10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


#  COPIES and viewing

In [46]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [48]:
print(np.shares_memory(a,b))

True


In [47]:
b[0]=10
print(a)
print(b)


[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [49]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [50]:
print(np.shares_memory(a,b))

False


# Random number generator

In [52]:
a=np.random.randint(0,20,15)
print(a)

[ 6  6 17 17  3 14 10 10 15  2 15  5  1  3  5]


In [54]:
mask=(a%2==0)

In [55]:
maskA=a[mask]
print(maskA)

[ 6  6 14 10 10  2]


In [56]:
a[maskA]=-1
print(a)

[ 6  6 -1 17  3 14 -1 10 15  2 -1  5  1  3 -1]


# Basic operators

In [5]:
import numpy as np
a=np.array([1,2,3,4])
print(a+1) #add1

[2 3 4 5]


In [6]:
 print(a**2) #square

[ 1  4  9 16]


In [7]:
print(a-2)

[-1  0  1  2]


In [8]:
print(a*2)

[2 4 6 8]


# all airthmetic operators elemnt wise

In [9]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [10]:
print(a*b)

[2. 4. 6. 8.]


In [11]:
print(a+b)

[3. 4. 5. 6.]


In [15]:
d=np.diag([1,2,3,4])
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [17]:
print(d*d)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [18]:
print(d.dot(d)) #predifened function

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# comparison operators

In [19]:
a=np.array([1,2,3,4])
b=np.array([5,2,6,4])
print(a==b) #elememt wise comparison

[False  True False  True]


In [20]:
print(a<b)

[ True False  True False]


In [21]:
print(a>b)

[False False False False]


In [22]:
#arrat wise compariosn
a=np.array([1,2,3,4])
b=np.array([6,2,5,4])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [23]:
print(np.array_equal(a,c))

True


# logical operators

In [25]:
a=np.array([1,1,0,0],dtype="bool")
b=np.array([1,0,1,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [26]:
print(np.logical_and(a,b))

[ True False False False]


# trignometry/teanscendental functions

In [29]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [30]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [31]:
np.log(a)

C:\Users\yvsur\AppData\Local\Temp\ipykernel_2020\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# basic reductions

In [43]:
x=np.array([1,2,3,4]) #sum of all elements in array
print(sum(x))

10


In [44]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [45]:
x.sum(axis=0)

array([4, 6])

In [46]:
x.sum(axis=1)

array([3, 7])